// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	server "github.com/nyan233/littlerpc/core/server"
)

// LittleRpcReflectionProxy is an autogenerated mock type for the LittleRpcReflectionProxy type
type LittleRpcReflectionProxy struct {
	mock.Mock
}

// AllCodec provides a mock function with given fields: ctx
func (_m *LittleRpcReflectionProxy) AllCodec(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllInstance provides a mock function with given fields: ctx
func (_m *LittleRpcReflectionProxy) AllInstance(ctx context.Context) (map[string]string, error) {
	ret := _m.Called(ctx)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(context.Context) map[string]string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AllPacker provides a mock function with given fields: ctx
func (_m *LittleRpcReflectionProxy) AllPacker(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MethodArgumentType provides a mock function with given fields: ctx, serviceName
func (_m *LittleRpcReflectionProxy) MethodArgumentType(ctx context.Context, serviceName string) ([]server.ArgumentType, error) {
	ret := _m.Called(ctx, serviceName)

	var r0 []server.ArgumentType
	if rf, ok := ret.Get(0).(func(context.Context, string) []server.ArgumentType); ok {
		r0 = rf(ctx, serviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]server.ArgumentType)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serviceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MethodTable provides a mock function with given fields: ctx, sourceName
func (_m *LittleRpcReflectionProxy) MethodTable(ctx context.Context, sourceName string) (*server.MethodTable, error) {
	ret := _m.Called(ctx, sourceName)

	var r0 *server.MethodTable
	if rf, ok := ret.Get(0).(func(context.Context, string) *server.MethodTable); ok {
		r0 = rf(ctx, sourceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*server.MethodTable)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sourceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewLittleRpcReflectionProxy interface {
	mock.TestingT
	Cleanup(func())
}

// NewLittleRpcReflectionProxy creates a new instance of LittleRpcReflectionProxy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLittleRpcReflectionProxy(t mockConstructorTestingTNewLittleRpcReflectionProxy) *LittleRpcReflectionProxy {
	mock := &LittleRpcReflectionProxy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
