// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v7.34.1
// source: namsserver.proto

package nameserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip          string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port        uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Priority    uint32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	IpBigEndian []byte `protobuf:"bytes,4,opt,name=ip_big_endian,json=ipBigEndian,proto3" json:"ip_big_endian,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Node) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Node) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Node) GetIpBigEndian() []byte {
	if x != nil {
		return x.IpBigEndian
	}
	return nil
}

type AddNodeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NodeList []*Node `protobuf:"bytes,2,rep,name=node_list,json=nodeList,proto3" json:"node_list,omitempty"`
}

func (x *AddNodeListReq) Reset() {
	*x = AddNodeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNodeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeListReq) ProtoMessage() {}

func (x *AddNodeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeListReq.ProtoReflect.Descriptor instead.
func (*AddNodeListReq) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{1}
}

func (x *AddNodeListReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddNodeListReq) GetNodeList() []*Node {
	if x != nil {
		return x.NodeList
	}
	return nil
}

type AddNodeListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *AddNodeListRsp) Reset() {
	*x = AddNodeListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNodeListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodeListRsp) ProtoMessage() {}

func (x *AddNodeListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodeListRsp.ProtoReflect.Descriptor instead.
func (*AddNodeListRsp) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{2}
}

func (x *AddNodeListRsp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AddNodeListRsp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetNodeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetNodeListReq) Reset() {
	*x = GetNodeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListReq) ProtoMessage() {}

func (x *GetNodeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListReq.ProtoReflect.Descriptor instead.
func (*GetNodeListReq) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeListReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetNodeListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version  uint32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	NodeList []*Node `protobuf:"bytes,3,rep,name=node_list,json=nodeList,proto3" json:"node_list,omitempty"`
}

func (x *GetNodeListRsp) Reset() {
	*x = GetNodeListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListRsp) ProtoMessage() {}

func (x *GetNodeListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListRsp.ProtoReflect.Descriptor instead.
func (*GetNodeListRsp) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeListRsp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetNodeListRsp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetNodeListRsp) GetNodeList() []*Node {
	if x != nil {
		return x.NodeList
	}
	return nil
}

type DeleteNodeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	NodeList []*Node `protobuf:"bytes,4,rep,name=node_list,json=nodeList,proto3" json:"node_list,omitempty"`
}

func (x *DeleteNodeListReq) Reset() {
	*x = DeleteNodeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNodeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeListReq) ProtoMessage() {}

func (x *DeleteNodeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeListReq.ProtoReflect.Descriptor instead.
func (*DeleteNodeListReq) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteNodeListReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteNodeListReq) GetNodeList() []*Node {
	if x != nil {
		return x.NodeList
	}
	return nil
}

type DeleteNodeListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version  uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	DelCount uint32 `protobuf:"varint,3,opt,name=del_count,json=delCount,proto3" json:"del_count,omitempty"`
}

func (x *DeleteNodeListRsp) Reset() {
	*x = DeleteNodeListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNodeListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeListRsp) ProtoMessage() {}

func (x *DeleteNodeListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeListRsp.ProtoReflect.Descriptor instead.
func (*DeleteNodeListRsp) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteNodeListRsp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteNodeListRsp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeleteNodeListRsp) GetDelCount() uint32 {
	if x != nil {
		return x.DelCount
	}
	return 0
}

type GetNodeListInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetNodeListInfoReq) Reset() {
	*x = GetNodeListInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeListInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListInfoReq) ProtoMessage() {}

func (x *GetNodeListInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListInfoReq.ProtoReflect.Descriptor instead.
func (*GetNodeListInfoReq) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{7}
}

func (x *GetNodeListInfoReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetNodeListInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key            string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version        uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	LastUpdatedAt  uint64 `protobuf:"varint,3,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	NodeListLength uint32 `protobuf:"varint,4,opt,name=node_list_length,json=nodeListLength,proto3" json:"node_list_length,omitempty"`
}

func (x *GetNodeListInfoRsp) Reset() {
	*x = GetNodeListInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeListInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListInfoRsp) ProtoMessage() {}

func (x *GetNodeListInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListInfoRsp.ProtoReflect.Descriptor instead.
func (*GetNodeListInfoRsp) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{8}
}

func (x *GetNodeListInfoRsp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetNodeListInfoRsp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetNodeListInfoRsp) GetLastUpdatedAt() uint64 {
	if x != nil {
		return x.LastUpdatedAt
	}
	return 0
}

func (x *GetNodeListInfoRsp) GetNodeListLength() uint32 {
	if x != nil {
		return x.NodeListLength
	}
	return 0
}

type GetAllKeyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllKeyReq) Reset() {
	*x = GetAllKeyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllKeyReq) ProtoMessage() {}

func (x *GetAllKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllKeyReq.ProtoReflect.Descriptor instead.
func (*GetAllKeyReq) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{9}
}

type GetAllKeyRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyList []string `protobuf:"bytes,1,rep,name=key_list,json=keyList,proto3" json:"key_list,omitempty"`
}

func (x *GetAllKeyRsp) Reset() {
	*x = GetAllKeyRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_namsserver_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllKeyRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllKeyRsp) ProtoMessage() {}

func (x *GetAllKeyRsp) ProtoReflect() protoreflect.Message {
	mi := &file_namsserver_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllKeyRsp.ProtoReflect.Descriptor instead.
func (*GetAllKeyRsp) Descriptor() ([]byte, []int) {
	return file_namsserver_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllKeyRsp) GetKeyList() []string {
	if x != nil {
		return x.KeyList
	}
	return nil
}

var File_namsserver_proto protoreflect.FileDescriptor

var file_namsserver_proto_rawDesc = []byte{
	0x0a, 0x10, 0x6e, 0x61, 0x6d, 0x73, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x6a,
	0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x70, 0x5f, 0x62, 0x69, 0x67,
	0x5f, 0x65, 0x6e, 0x64, 0x69, 0x61, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x69,
	0x70, 0x42, 0x69, 0x67, 0x45, 0x6e, 0x64, 0x69, 0x61, 0x6e, 0x22, 0x51, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2d,
	0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3c, 0x0a,
	0x0e, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x22, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x6b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a,
	0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x11,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x5c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x26, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e,
	0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x0e, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x22, 0x29, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x52, 0x73, 0x70, 0x12, 0x19, 0x0a,
	0x08, 0x6b, 0x65, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xfe, 0x02, 0x0a, 0x0a, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x45,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x51, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x18, 0x2e, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x4b, 0x65, 0x79, 0x52, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x62, 0x2f,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_namsserver_proto_rawDescOnce sync.Once
	file_namsserver_proto_rawDescData = file_namsserver_proto_rawDesc
)

func file_namsserver_proto_rawDescGZIP() []byte {
	file_namsserver_proto_rawDescOnce.Do(func() {
		file_namsserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_namsserver_proto_rawDescData)
	})
	return file_namsserver_proto_rawDescData
}

var file_namsserver_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_namsserver_proto_goTypes = []interface{}{
	(*Node)(nil),               // 0: nameserver.Node
	(*AddNodeListReq)(nil),     // 1: nameserver.AddNodeListReq
	(*AddNodeListRsp)(nil),     // 2: nameserver.AddNodeListRsp
	(*GetNodeListReq)(nil),     // 3: nameserver.GetNodeListReq
	(*GetNodeListRsp)(nil),     // 4: nameserver.GetNodeListRsp
	(*DeleteNodeListReq)(nil),  // 5: nameserver.DeleteNodeListReq
	(*DeleteNodeListRsp)(nil),  // 6: nameserver.DeleteNodeListRsp
	(*GetNodeListInfoReq)(nil), // 7: nameserver.GetNodeListInfoReq
	(*GetNodeListInfoRsp)(nil), // 8: nameserver.GetNodeListInfoRsp
	(*GetAllKeyReq)(nil),       // 9: nameserver.GetAllKeyReq
	(*GetAllKeyRsp)(nil),       // 10: nameserver.GetAllKeyRsp
}
var file_namsserver_proto_depIdxs = []int32{
	0,  // 0: nameserver.AddNodeListReq.node_list:type_name -> nameserver.Node
	0,  // 1: nameserver.GetNodeListRsp.node_list:type_name -> nameserver.Node
	0,  // 2: nameserver.DeleteNodeListReq.node_list:type_name -> nameserver.Node
	1,  // 3: nameserver.nameserver.AddNodeList:input_type -> nameserver.AddNodeListReq
	3,  // 4: nameserver.nameserver.GetNodeList:input_type -> nameserver.GetNodeListReq
	5,  // 5: nameserver.nameserver.DeleteNodeList:input_type -> nameserver.DeleteNodeListReq
	7,  // 6: nameserver.nameserver.GetNodeListInfo:input_type -> nameserver.GetNodeListInfoReq
	9,  // 7: nameserver.nameserver.GetAllKey:input_type -> nameserver.GetAllKeyReq
	2,  // 8: nameserver.nameserver.AddNodeList:output_type -> nameserver.AddNodeListRsp
	4,  // 9: nameserver.nameserver.GetNodeList:output_type -> nameserver.GetNodeListRsp
	6,  // 10: nameserver.nameserver.DeleteNodeList:output_type -> nameserver.DeleteNodeListRsp
	8,  // 11: nameserver.nameserver.GetNodeListInfo:output_type -> nameserver.GetNodeListInfoRsp
	10, // 12: nameserver.nameserver.GetAllKey:output_type -> nameserver.GetAllKeyRsp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_namsserver_proto_init() }
func file_namsserver_proto_init() {
	if File_namsserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_namsserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNodeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNodeListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNodeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNodeListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeListInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeListInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllKeyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_namsserver_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllKeyRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_namsserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_namsserver_proto_goTypes,
		DependencyIndexes: file_namsserver_proto_depIdxs,
		MessageInfos:      file_namsserver_proto_msgTypes,
	}.Build()
	File_namsserver_proto = out.File
	file_namsserver_proto_rawDesc = nil
	file_namsserver_proto_goTypes = nil
	file_namsserver_proto_depIdxs = nil
}
