// Code generated by protoc-gen-go. DO NOT EDIT.
// source: namsserver.proto

package nameserver // import "pb/nameserver"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Node struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Priority             uint32   `protobuf:"varint,3,opt,name=priority" json:"priority,omitempty"`
	IpBigEndian          []byte   `protobuf:"bytes,4,opt,name=ip_big_endian,json=ipBigEndian,proto3" json:"ip_big_endian,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Node) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Node) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Node) GetIpBigEndian() []byte {
	if m != nil {
		return m.IpBigEndian
	}
	return nil
}

type AddNodeListReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	NodeList             []*Node  `protobuf:"bytes,2,rep,name=node_list,json=nodeList" json:"node_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *AddNodeListReq) Reset()         { *m = AddNodeListReq{} }
func (m *AddNodeListReq) String() string { return proto.CompactTextString(m) }
func (*AddNodeListReq) ProtoMessage()    {}
func (*AddNodeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{1}
}
func (m *AddNodeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeListReq.Unmarshal(m, b)
}
func (m *AddNodeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeListReq.Marshal(b, m, deterministic)
}
func (dst *AddNodeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeListReq.Merge(dst, src)
}
func (m *AddNodeListReq) XXX_Size() int {
	return xxx_messageInfo_AddNodeListReq.Size(m)
}
func (m *AddNodeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeListReq proto.InternalMessageInfo

func (m *AddNodeListReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddNodeListReq) GetNodeList() []*Node {
	if m != nil {
		return m.NodeList
	}
	return nil
}

type AddNodeListRsp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *AddNodeListRsp) Reset()         { *m = AddNodeListRsp{} }
func (m *AddNodeListRsp) String() string { return proto.CompactTextString(m) }
func (*AddNodeListRsp) ProtoMessage()    {}
func (*AddNodeListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{2}
}
func (m *AddNodeListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNodeListRsp.Unmarshal(m, b)
}
func (m *AddNodeListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNodeListRsp.Marshal(b, m, deterministic)
}
func (dst *AddNodeListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNodeListRsp.Merge(dst, src)
}
func (m *AddNodeListRsp) XXX_Size() int {
	return xxx_messageInfo_AddNodeListRsp.Size(m)
}
func (m *AddNodeListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNodeListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddNodeListRsp proto.InternalMessageInfo

func (m *AddNodeListRsp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *AddNodeListRsp) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetNodeListReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetNodeListReq) Reset()         { *m = GetNodeListReq{} }
func (m *GetNodeListReq) String() string { return proto.CompactTextString(m) }
func (*GetNodeListReq) ProtoMessage()    {}
func (*GetNodeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{3}
}
func (m *GetNodeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeListReq.Unmarshal(m, b)
}
func (m *GetNodeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeListReq.Marshal(b, m, deterministic)
}
func (dst *GetNodeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeListReq.Merge(dst, src)
}
func (m *GetNodeListReq) XXX_Size() int {
	return xxx_messageInfo_GetNodeListReq.Size(m)
}
func (m *GetNodeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeListReq proto.InternalMessageInfo

func (m *GetNodeListReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetNodeListRsp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	NodeList             []*Node  `protobuf:"bytes,3,rep,name=node_list,json=nodeList" json:"node_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetNodeListRsp) Reset()         { *m = GetNodeListRsp{} }
func (m *GetNodeListRsp) String() string { return proto.CompactTextString(m) }
func (*GetNodeListRsp) ProtoMessage()    {}
func (*GetNodeListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{4}
}
func (m *GetNodeListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeListRsp.Unmarshal(m, b)
}
func (m *GetNodeListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeListRsp.Marshal(b, m, deterministic)
}
func (dst *GetNodeListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeListRsp.Merge(dst, src)
}
func (m *GetNodeListRsp) XXX_Size() int {
	return xxx_messageInfo_GetNodeListRsp.Size(m)
}
func (m *GetNodeListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeListRsp proto.InternalMessageInfo

func (m *GetNodeListRsp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetNodeListRsp) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetNodeListRsp) GetNodeList() []*Node {
	if m != nil {
		return m.NodeList
	}
	return nil
}

type DeleteNodeListReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	NodeList             []*Node  `protobuf:"bytes,4,rep,name=node_list,json=nodeList" json:"node_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteNodeListReq) Reset()         { *m = DeleteNodeListReq{} }
func (m *DeleteNodeListReq) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeListReq) ProtoMessage()    {}
func (*DeleteNodeListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{5}
}
func (m *DeleteNodeListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeListReq.Unmarshal(m, b)
}
func (m *DeleteNodeListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeListReq.Marshal(b, m, deterministic)
}
func (dst *DeleteNodeListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeListReq.Merge(dst, src)
}
func (m *DeleteNodeListReq) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeListReq.Size(m)
}
func (m *DeleteNodeListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeListReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeListReq proto.InternalMessageInfo

func (m *DeleteNodeListReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteNodeListReq) GetNodeList() []*Node {
	if m != nil {
		return m.NodeList
	}
	return nil
}

type DeleteNodeListRsp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	DelCount             uint32   `protobuf:"varint,3,opt,name=del_count,json=delCount" json:"del_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteNodeListRsp) Reset()         { *m = DeleteNodeListRsp{} }
func (m *DeleteNodeListRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteNodeListRsp) ProtoMessage()    {}
func (*DeleteNodeListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{6}
}
func (m *DeleteNodeListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteNodeListRsp.Unmarshal(m, b)
}
func (m *DeleteNodeListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteNodeListRsp.Marshal(b, m, deterministic)
}
func (dst *DeleteNodeListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeListRsp.Merge(dst, src)
}
func (m *DeleteNodeListRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteNodeListRsp.Size(m)
}
func (m *DeleteNodeListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeListRsp proto.InternalMessageInfo

func (m *DeleteNodeListRsp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteNodeListRsp) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *DeleteNodeListRsp) GetDelCount() uint32 {
	if m != nil {
		return m.DelCount
	}
	return 0
}

type GetNodeListInfoReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetNodeListInfoReq) Reset()         { *m = GetNodeListInfoReq{} }
func (m *GetNodeListInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetNodeListInfoReq) ProtoMessage()    {}
func (*GetNodeListInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{7}
}
func (m *GetNodeListInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeListInfoReq.Unmarshal(m, b)
}
func (m *GetNodeListInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeListInfoReq.Marshal(b, m, deterministic)
}
func (dst *GetNodeListInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeListInfoReq.Merge(dst, src)
}
func (m *GetNodeListInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetNodeListInfoReq.Size(m)
}
func (m *GetNodeListInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeListInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeListInfoReq proto.InternalMessageInfo

func (m *GetNodeListInfoReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetNodeListInfoRsp struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Version              uint32   `protobuf:"varint,2,opt,name=version" json:"version,omitempty"`
	LastUpdatedAt        uint64   `protobuf:"varint,3,opt,name=last_updated_at,json=lastUpdatedAt" json:"last_updated_at,omitempty"`
	NodeListLength       uint32   `protobuf:"varint,4,opt,name=node_list_length,json=nodeListLength" json:"node_list_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetNodeListInfoRsp) Reset()         { *m = GetNodeListInfoRsp{} }
func (m *GetNodeListInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetNodeListInfoRsp) ProtoMessage()    {}
func (*GetNodeListInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{8}
}
func (m *GetNodeListInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeListInfoRsp.Unmarshal(m, b)
}
func (m *GetNodeListInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeListInfoRsp.Marshal(b, m, deterministic)
}
func (dst *GetNodeListInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeListInfoRsp.Merge(dst, src)
}
func (m *GetNodeListInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetNodeListInfoRsp.Size(m)
}
func (m *GetNodeListInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeListInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeListInfoRsp proto.InternalMessageInfo

func (m *GetNodeListInfoRsp) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetNodeListInfoRsp) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetNodeListInfoRsp) GetLastUpdatedAt() uint64 {
	if m != nil {
		return m.LastUpdatedAt
	}
	return 0
}

func (m *GetNodeListInfoRsp) GetNodeListLength() uint32 {
	if m != nil {
		return m.NodeListLength
	}
	return 0
}

type GetAllKeyReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetAllKeyReq) Reset()         { *m = GetAllKeyReq{} }
func (m *GetAllKeyReq) String() string { return proto.CompactTextString(m) }
func (*GetAllKeyReq) ProtoMessage()    {}
func (*GetAllKeyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{9}
}
func (m *GetAllKeyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllKeyReq.Unmarshal(m, b)
}
func (m *GetAllKeyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllKeyReq.Marshal(b, m, deterministic)
}
func (dst *GetAllKeyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllKeyReq.Merge(dst, src)
}
func (m *GetAllKeyReq) XXX_Size() int {
	return xxx_messageInfo_GetAllKeyReq.Size(m)
}
func (m *GetAllKeyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllKeyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllKeyReq proto.InternalMessageInfo

type GetAllKeyRsp struct {
	KeyList              []string `protobuf:"bytes,1,rep,name=key_list,json=keyList" json:"key_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetAllKeyRsp) Reset()         { *m = GetAllKeyRsp{} }
func (m *GetAllKeyRsp) String() string { return proto.CompactTextString(m) }
func (*GetAllKeyRsp) ProtoMessage()    {}
func (*GetAllKeyRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_namsserver_b37fc8572e75ca78, []int{10}
}
func (m *GetAllKeyRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllKeyRsp.Unmarshal(m, b)
}
func (m *GetAllKeyRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllKeyRsp.Marshal(b, m, deterministic)
}
func (dst *GetAllKeyRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllKeyRsp.Merge(dst, src)
}
func (m *GetAllKeyRsp) XXX_Size() int {
	return xxx_messageInfo_GetAllKeyRsp.Size(m)
}
func (m *GetAllKeyRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllKeyRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllKeyRsp proto.InternalMessageInfo

func (m *GetAllKeyRsp) GetKeyList() []string {
	if m != nil {
		return m.KeyList
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "nameserver.Node")
	proto.RegisterType((*AddNodeListReq)(nil), "nameserver.AddNodeListReq")
	proto.RegisterType((*AddNodeListRsp)(nil), "nameserver.AddNodeListRsp")
	proto.RegisterType((*GetNodeListReq)(nil), "nameserver.GetNodeListReq")
	proto.RegisterType((*GetNodeListRsp)(nil), "nameserver.GetNodeListRsp")
	proto.RegisterType((*DeleteNodeListReq)(nil), "nameserver.DeleteNodeListReq")
	proto.RegisterType((*DeleteNodeListRsp)(nil), "nameserver.DeleteNodeListRsp")
	proto.RegisterType((*GetNodeListInfoReq)(nil), "nameserver.GetNodeListInfoReq")
	proto.RegisterType((*GetNodeListInfoRsp)(nil), "nameserver.GetNodeListInfoRsp")
	proto.RegisterType((*GetAllKeyReq)(nil), "nameserver.GetAllKeyReq")
	proto.RegisterType((*GetAllKeyRsp)(nil), "nameserver.GetAllKeyRsp")
}

func init() { proto.RegisterFile("namsserver.proto", fileDescriptor_namsserver_b37fc8572e75ca78) }

var fileDescriptor_namsserver_b37fc8572e75ca78 = []byte{
	// 473 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0x45, 0xb6, 0x68, 0xac, 0x71, 0x24, 0xbb, 0x73, 0x52, 0x55, 0x5a, 0xcc, 0x1e, 0x82, 0x7a,
	0xa8, 0x0b, 0xe9, 0xb5, 0x50, 0x9c, 0x36, 0x84, 0xd2, 0x10, 0x88, 0x68, 0x2f, 0xa5, 0x20, 0xe4,
	0xee, 0xd4, 0xdd, 0x5a, 0xd9, 0xdd, 0x68, 0x37, 0x01, 0xfd, 0x8d, 0xfe, 0xe0, 0x12, 0x24, 0x7f,
	0x44, 0x8a, 0x63, 0x07, 0xdf, 0x76, 0xe6, 0x8d, 0xdf, 0xcc, 0xbc, 0x79, 0x16, 0x0c, 0x65, 0x76,
	0x65, 0x0c, 0x15, 0xb7, 0x54, 0x8c, 0x75, 0xa1, 0xac, 0x42, 0x90, 0xd9, 0x15, 0x2d, 0x32, 0xec,
	0x2f, 0xb8, 0x17, 0x8a, 0x13, 0x06, 0xd0, 0x11, 0x3a, 0x74, 0x46, 0x4e, 0xec, 0x25, 0x1d, 0xa1,
	0x11, 0xc1, 0xd5, 0xaa, 0xb0, 0x61, 0x67, 0xe4, 0xc4, 0x7e, 0x52, 0xbf, 0x31, 0x82, 0x9e, 0x2e,
	0x84, 0x2a, 0x84, 0x2d, 0xc3, 0x6e, 0x9d, 0x5f, 0xc7, 0xc8, 0xc0, 0x17, 0x3a, 0x9d, 0x8a, 0x59,
	0x4a, 0x92, 0x8b, 0x4c, 0x86, 0xee, 0xc8, 0x89, 0x0f, 0x93, 0xbe, 0xd0, 0x27, 0x62, 0x76, 0x5a,
	0xa7, 0xd8, 0x25, 0x04, 0x13, 0xce, 0xab, 0x76, 0xe7, 0xc2, 0xd8, 0x84, 0xae, 0x71, 0x08, 0xdd,
	0x39, 0x95, 0xcb, 0xb6, 0xd5, 0x13, 0xdf, 0x82, 0x27, 0x15, 0xa7, 0x34, 0x17, 0xa6, 0x6a, 0xde,
	0x8d, 0xfb, 0xc7, 0xc3, 0xf1, 0xfd, 0xbc, 0xe3, 0xea, 0xd7, 0x49, 0x4f, 0x2e, 0x39, 0xd8, 0x87,
	0x36, 0xa5, 0xd1, 0x8f, 0x50, 0x86, 0x70, 0x70, 0x4b, 0x85, 0x11, 0x4a, 0x2e, 0xb7, 0x59, 0x85,
	0x8c, 0x41, 0x70, 0x46, 0x76, 0xe7, 0x40, 0x6c, 0xde, 0xae, 0xd9, 0xaf, 0x43, 0x7b, 0x9d, 0xee,
	0x93, 0xeb, 0x7c, 0x83, 0xe7, 0x9f, 0x29, 0x27, 0x4b, 0x7b, 0x88, 0xe4, 0x3e, 0xc9, 0xfa, 0x73,
	0x83, 0x75, 0xcf, 0x2d, 0x5e, 0x82, 0xc7, 0x29, 0x4f, 0x7f, 0xa9, 0x1b, 0x69, 0x57, 0x97, 0xe7,
	0x94, 0x7f, 0xaa, 0x62, 0x76, 0x04, 0xd8, 0x10, 0xe8, 0x8b, 0xfc, 0xad, 0x1e, 0x17, 0xf2, 0x9f,
	0xb3, 0x59, 0xb8, 0xe7, 0x1c, 0x47, 0x30, 0xc8, 0x33, 0x63, 0xd3, 0x1b, 0xcd, 0x33, 0x4b, 0x3c,
	0xcd, 0x16, 0xd3, 0xb8, 0x89, 0x5f, 0xa5, 0xbf, 0x2f, 0xb2, 0x13, 0x8b, 0x31, 0x0c, 0xd7, 0xfa,
	0xa4, 0x39, 0xc9, 0x99, 0xfd, 0x53, 0xfb, 0xd1, 0x4f, 0x82, 0x95, 0x28, 0xe7, 0x75, 0x96, 0x05,
	0x70, 0x78, 0x46, 0x76, 0x92, 0xe7, 0x5f, 0xa9, 0x4c, 0xe8, 0x9a, 0xbd, 0x69, 0xc6, 0x46, 0xe3,
	0x0b, 0xe8, 0xcd, 0xa9, 0x5c, 0x08, 0xed, 0x8c, 0xba, 0xb1, 0x97, 0x1c, 0xcc, 0xa9, 0xac, 0x08,
	0x8e, 0xff, 0x77, 0xa0, 0xf1, 0x47, 0xc2, 0x53, 0xe8, 0x37, 0x9c, 0x88, 0x51, 0xf3, 0x1e, 0x6d,
	0xd7, 0x47, 0x5b, 0x31, 0xa3, 0x2b, 0x9a, 0x86, 0x48, 0x6d, 0x9a, 0xb6, 0x57, 0xa3, 0xad, 0x98,
	0xd1, 0x78, 0x01, 0x41, 0xfb, 0xe4, 0xf8, 0xaa, 0x59, 0xbd, 0x61, 0xb2, 0x68, 0x17, 0x6c, 0x34,
	0x5e, 0xc2, 0xe0, 0xc1, 0xed, 0xf0, 0xf5, 0x96, 0xf6, 0x4b, 0x07, 0x44, 0x3b, 0x71, 0xa3, 0xf1,
	0x23, 0x78, 0x6b, 0xa9, 0x31, 0x7c, 0x50, 0xbc, 0xbe, 0x48, 0xb4, 0x05, 0x31, 0xfa, 0x64, 0xf0,
	0xc3, 0xd7, 0xd3, 0x77, 0xf7, 0xe8, 0xf4, 0x59, 0xfd, 0x79, 0x7b, 0x7f, 0x17, 0x00, 0x00, 0xff,
	0xff, 0x77, 0x75, 0x61, 0xba, 0xf2, 0x04, 0x00, 0x00,
}
