// Code generated by protoc-gen-go-lrpc. DO NOT EDIT.
package nameserver

/*
   @Generator   : protoc-gen-go-lrpc
   @CreateTime  : 2026-06-11 01:37:05.349284 +0800 CST
   @Author      : NoAuthor
   @Comment     : code is auto generate do not edit
*/

import (
	"github.com/nyan233/littlerpc/core/common/context"
	"github.com/nyan233/littlerpc/core/common/metadata"
	"github.com/nyan233/littlerpc/core/server"
)

type NameserverServer interface {
	// 添加节点
	AddNodeList(ctx *context.Context, req *AddNodeListReq) (rsp *AddNodeListRsp, err error)
	// 获取节点
	GetNodeList(ctx *context.Context, req *GetNodeListReq) (rsp *GetNodeListRsp, err error)
	// 删除节点
	DeleteNodeList(ctx *context.Context, req *DeleteNodeListReq) (rsp *DeleteNodeListRsp, err error)
	// 获取节点信息
	// 可以比较version来判断是否更新
	GetNodeListInfo(ctx *context.Context, req *GetNodeListInfoReq) (rsp *GetNodeListInfoRsp, err error)
	// 获取所有的key
	GetAllKey(ctx *context.Context, req *GetAllKeyReq) (rsp *GetAllKeyRsp, err error)
}

type UnImplNameserverServer struct{}

func (s UnImplNameserverServer) AddNodeList(ctx *context.Context, req *AddNodeListReq) (rsp *AddNodeListRsp, err error) {
	panic("not implemented")
}

func (s UnImplNameserverServer) GetNodeList(ctx *context.Context, req *GetNodeListReq) (rsp *GetNodeListRsp, err error) {
	panic("not implemented")
}

func (s UnImplNameserverServer) DeleteNodeList(ctx *context.Context, req *DeleteNodeListReq) (rsp *DeleteNodeListRsp, err error) {
	panic("not implemented")
}

func (s UnImplNameserverServer) GetNodeListInfo(ctx *context.Context, req *GetNodeListInfoReq) (rsp *GetNodeListInfoRsp, err error) {
	panic("not implemented")
}

func (s UnImplNameserverServer) GetAllKey(ctx *context.Context, req *GetAllKeyReq) (rsp *GetAllKeyRsp, err error) {
	panic("not implemented")
}

var NameserverServerDesc = server.Desc{
	Package: "nameserver",
	ServiceMethods: map[string][]server.ServiceMethod{
		"nameserver": {
			{
				Name:    "AddNodeList",
				Options: nil,
			},
			{
				Name:    "GetNodeList",
				Options: nil,
			},
			{
				Name:    "DeleteNodeList",
				Options: nil,
			},
			{
				Name:    "GetNodeListInfo",
				Options: nil,
			},
			{
				Name:    "GetAllKey",
				Options: nil,
			},
		},
	},
}

func RegisterNameserverServer(s *server.Server, i interface{}, option map[string]metadata.ProcessOption) error {
	_ = i.(NameserverServer)
	return s.RegisterClass("nameserver", i, option)
}
